
export const items = [
    {id: 1, name: "pretodauwdauiefiubfe", price: 10.00, image: require("../assets/images/Logo.png") },
    {id: 2, name: "preto", price: 10.00, image: require("../assets/images/Logo.png") },
    {id: 3, name: "rosa", price: 10.00, image: require("../assets/images/Logo.png") },
    {id: 4, name: "rosa", price: 10.00, image: require("../assets/images/Logo.png") },
    {id: 5, name: "rosa", price: 10.00, image: require("../assets/images/Logo.png") },
    {id: 6, name: "rosa", price: 10.00, image: require("../assets/images/Logo.png") },
    {id: 7, name: "preto", price: 10.00, image: require("../assets/images/Logo.png") },
    {id: 8, name: "preto", price: 10.00, image: require("../assets/images/Logo.png") },
    {id: 9, name: "rosa", price: 10.00, image: require("../assets/images/Logo.png") },
    {id: 10, name: "rosa", price: 10.00, image: require("../assets/images/Logo.png") },
    {id: 11, name: "rosa", price: 10.00, image: require("../assets/images/Logo.png") },
    {id: 12, name: "rosa", price: 10.00, image: require("../assets/images/Logo.png") },
    {id: 13, name: "preto", price: 10.00, image: require("../assets/images/Logo.png") },
    {id: 14, name: "preto", price: 10.00, image: require("../assets/images/Logo.png") },
    {id: 15, name: "rosa", price: 10.00, image: require("../assets/images/Logo.png") },
    {id: 16, name: "rosa", price: 10.00, image: require("../assets/images/Logo.png") },
    {id: 17, name: "rosa", price: 10.00, image: require("../assets/images/Logo.png") },
    {id: 18, name: "rosa", price: 10.00, image: require("../assets/images/Logo.png") },
    {id: 19, name: "preto", price: 10.00, image: require("../assets/images/Logo.png") },
    {id: 20, name: "preto", price: 10.00, image: require("../assets/images/Logo.png") },
    {id: 21, name: "rosa", price: 10.00, image: require("../assets/images/Logo.png") },
    {id: 22, name: "rosa", price: 10.00, image: require("../assets/images/Logo.png") },
    {id: 23, name: "rosa", price: 10.00, image: require("../assets/images/Logo.png") },
    {id: 24, name: "preto", price: 10.00, image: require("../assets/images/Logo.png") },
    {id: 25, name: "preto", price: 10.00, image: require("../assets/images/Logo.png") },
    {id: 26, name: "rosa", price: 10.00, image: require("../assets/images/Logo.png") },
    {id: 27, name: "rosa", price: 10.00, image: require("../assets/images/Logo.png") },
    {id: 28, name: "rosa", price: 10.00, image: require("../assets/images/Logo.png") },
    {id: 29, name: "rosa", price: 10.00, image: require("../assets/images/Logo.png") },
    {id: 30, name: "preto", price: 10.00, image: require("../assets/images/Logo.png") },
    {id: 31, name: "preto", price: 10.00, image: require("../assets/images/Logo.png") },
    {id: 32, name: "rosa", price: 10.00, image: require("../assets/images/Logo.png") },
    {id: 33, name: "rosa", price: 10.00, image: require("../assets/images/Logo.png") },
    {id: 34, name: "rosa", price: 10.00, image: require("../assets/images/Logo.png") },
    {id: 35, name: "rosa", price: 10.00, image: require("../assets/images/Logo.png") },
    {id: 36, name: "preto", price: 10.00, image: require("../assets/images/Logo.png") },
    {id: 37, name: "preto", price: 10.00, image: require("../assets/images/Logo.png") },
    {id: 38, name: "rosa", price: 10.00, image: require("../assets/images/Logo.png") },
    {id: 39, name: "rosa", price: 10.00, image: require("../assets/images/Logo.png") },
    {id: 40, name: "rosa", price: 10.00, image: require("../assets/images/Logo.png") },
    {id: 41, name: "rosa", price: 10.00, image: require("../assets/images/Logo.png") },
    {id: 42, name: "preto", price: 10.00, image: require("../assets/images/Logo.png") },
    {id: 43, name: "preto", price: 10.00, image: require("../assets/images/Logo.png") },
    {id: 44, name: "rosa", price: 10.00, image: require("../assets/images/Logo.png") },
    {id: 45, name: "rosa", price: 10.00, image: require("../assets/images/Logo.png") },
    {id: 46, name: "rosa", price: 10.00, image: require("../assets/images/Logo.png") },
   
   


];